name: Docker Image Build

on:
  push:
    branches:
      - main
    paths:
      - packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ./packages
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          IMAGE_TAGGED="xtechnology/${{ github.event.repository.name }}:${GITHUB_SHA}"
          IMAGE_LATEST="xtechnology/${{ github.event.repository.name }}:latest"
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
          docker build -t ${IMAGE_TAGGED} -t ${IMAGE_LATEST} .
          docker push ${IMAGE_TAGGED}
          docker push ${IMAGE_LATEST}
          docker logout
